name: CI

on:
  push:
    branches: [ master ]

env:
  super_secret: ${{ secrets.NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get /syedsair/OpenCV-AI-Face-Recognizer
        run: |
          sudo mkdir /syedsair
          sudo chmod -R 777 /syedsair
          cd /syedsair
          git clone https://github.com/syedsair/OpenCV-AI-Face-Recognizer

      - name: Get /syedsair/OpenCV-AI-Face-Recognizer
        run: |
          cd /syedsair
          git clone https://github.com/syedsair/OpenCV-AI-Face-Recognizer

      - name: Run my build script
        run: |
          cd /syedsair/OpenCV-AI-Face-Recognizer
          ./build.sh /syedsair/OpenCV-AI-Face-Recognizer
