name: Greeting on variable day

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v2
      - name: Run a one liner script
        run: sh ./namer.sh
