name: GitHub Actions Demo
on: [push,pull_request]
jobs:
  Check-Leaked-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: '2'
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
        
      - name: Check out repository code Again
        uses: actions/checkout@v3
        
      - run: echo "HERE"
        
      - run: echo "💡 Check Completed!"
