name: CI

on:
  push:
    branches: [ master ]

env:
  super_secret: ${{ secrets.NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print It
        run: |
          echo ${{ secrets.NAME }}

