name: GitHub Actions Demo
on: [push,pull_request]
jobs:
  Check-Leaked-Secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: gitleaks-action
        uses: zricethezav/gitleaks-action@master
      - run: echo "💡 Check Completed!"
